apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: {{.Values.node.name}}
    helm.sh/chart: {{ printf "%s-%s" .Chart.Name .Chart.Version }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/part-of: {{ .Chart.Name }}
  name: {{.Values.node.name}}
rules:
  - apiGroups:
      - ""
    resources:
      - nodes
      - nodes/stats
      - nodes/metrics
    verbs:
      - get
      - watch
      - list
  - apiGroups:
      - ''
    resources:
      - pods
    verbs:
      - list
  - apiGroups:
      - ''
    resources:
      - namespaces
    verbs:
      - list
      - get
  - nonResourceURLs:
      - /metrics/cadvisor
    verbs:
      - get
      - watch
      - list