apiVersion: v1
kind: Secret
metadata:
  name: {{.Release.Name}}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    helm.sh/chart: {{ printf "%s-%s" .Chart.Name .Chart.Version }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/part-of: {{ .Chart.Name }}
type: Opaque
stringData:
  KCM_ORG_ID: {{ .Values.kcm.orgId  | quote}}
  KCM_ADDR: {{ .Values.kcm.addr  | quote}}
  KCM_TOKEN: {{ .Values.kcm.token  | quote}}
  KCM_INSECURE: {{ .Values.kcm.insecure | quote}}
