clusterName: "lucida-kcm"
image: ""
pullPolicy: "Always"
kcm:
  orgId: ""
  addr: ""
  token: ""
  insecure: false

master:
  name: "kcm-master-agent"
  insecure: true
  port: 4222
  healthCheckPort: 8080
  resources:
    limits:
      cpu: "250m"
      memory: "512Mi"
    requests:
        cpu: "50m"
        memory: "50Mi"

node:
  name: "kcm-node-agent"
  healthCheckPort: 8080
  resources:
    limits:
      cpu: "100m"
      memory: "128Mi"
    requests:
        cpu: "10m"
        memory: "32Mi"

